# Generated by Django 3.1.4 on 2021-11-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_auto_20211101_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_db',
            name='booked_by',
        ),
    ]
